### PR TITLE
fixed proxies in karma config

### PR DESCRIPTION
**Pull request by kresli**
The last pull request will brake the proxies soon as you run `jspm install`. The reason is that jspm will replace

```
"github:*": "src/jspm_packages/github/*",
"npm:*": "src/jspm_packages/npm/*"
```

by

```
"github:*": "jspm_packages/github/*",
"npm:*": "jspm_packages/npm/*"
```

in `config.js`

### CODE REVIEW

**Comment by gunnarlium** [comment]
Hmm. Both this one and the previous one works fine locally for me, running node v4.2.1, but both fails on node v5. Which version are you using?

**Comment by kresli** [comment]
karma is not ready for node 5 as far as I know. Im using `4.1.1`. Even though the test passed, the browser will throw error because it is looking for `jspm_dependencies` with wrong path. `baseUrl` was set on `/` so your packages are in `src/jspm_packages` for the browser. I've cheat it by adding `src` in front of paths in `config.js`. The important thing is to keep correct path in `baseUrl`.

**Comment by gunnarlium** [comment]
Can you provide some code to reproduce?

Do I understand correctly that the problem only happens when you run this in a browser? In that case, I think the path will depend on what your document root is. I expect the document root to be in the `src` folder.

**Comment by kresli** [comment]
> Do I understand correctly that the problem only happens when you run this in a browser? 

Yes

> I expect the document root to be in the src folder.

Thats why I replaced `baseURL: '\'` by `baseURL:'\src` in `config.js`

> Can you provide some code to reproduce?

Soon as I will have some spare time I can create test branch with index.html if you want

**Pull request closed without merging**
